In [8]:
import numpy as np


In [9]:
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])

print(matrix_a)
print(matrix_b)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
print(matrix_a + matrix_b)

[[ 6  8]
 [10 12]]


In [11]:
print(matrix_a - matrix_b)
print(matrix_a * matrix_b)
print(matrix_a * 5)

[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 10]
 [15 20]]


In [26]:
matrix_a

array([[1, 2],
       [3, 4]])

In [27]:
print(matrix_a @ matrix_b)

[[19 22]
 [43 50]]


In [37]:
matrix_1 = np.array([[1,2,3],[2,3,4]])

In [29]:
print(matrix_1 - matrix_2)

[[-4 -4]
 [-5 -5]
 [-6 -6]]


In [30]:
matrix_1.T

array([[1, 2, 3],
       [2, 3, 4]])

In [38]:
matrix_2 = np.array([[1,2,3,4],[4,5,4,4],[7,8,9,4]])
matrix_2

array([[1, 2, 3, 4],
       [4, 5, 4, 4],
       [7, 8, 9, 4]])

In [39]:
print(matrix_1 @ matrix_2)

[[30 36 38 24]
 [42 51 54 36]]
