In [2]:
import numpy as np
from numpy.ma.core import argmax

In [3]:
A = np.array([[1,2],
              [3,4]])
print(A)
print("Dtype of Matrix",A.dtype)

[[1 2]
 [3 4]]
Dtype of Matrix int64


In [5]:
B = np.array([[2.3  , 3.4],
             [3.21 , 3.13]])
print(B)
print("Dtype of Matrix" ,B.dtype)

[[2.3  3.4 ]
 [3.21 3.13]]
Dtype of Matrix float64


In [9]:
C = np.array([['sq','aaf'],
              ['asd','asssssssssssssfd']],dtype="<U4")
print(C)
print("Dtype of Matrix",C.dtype)

[['sq' 'aaf']
 ['asd' 'asss']]
Dtype of Matrix <U4


In [10]:
A = A.astype(np.float32)
print(A.dtype)

float32


In [11]:
R = np.random.randn(2,3)
print(R)

[[-0.17375902  0.42581826  2.03328935]
 [ 1.17608215 -0.76863673 -0.0681119 ]]


In [1]:
import numpy as np
R = np.random.uniform(low=-1,high=1,size=(2,3))
print(R)
A = np.random.randint(low=0,high=7,size=(3,6))
print(A)
# Dinh dang npy
np.save('E:\Python\Road to OLP AI 20 days\Day 1 - Python Data Science\A\A.npy',A)
# Dinh dang txt
np.savetxt('E:\Python\Road to OLP AI 20 days\Day 1 - Python Data Science\A\K.txt',A)
# List cac file 
!ls -a "E:\Python\Road to OLP AI 20 days\Day 1 - Python Data Science\A"

[[ 0.26928366  0.30790613 -0.40561097]
 [ 0.77078208  0.53497788  0.48546478]]
[[4 5 1 6 1 6]
 [1 0 3 3 1 2]
 [0 5 1 1 4 3]]
.
..
A.npy
K.txt


In [6]:
np.loadtxt("E:\Python\Road to OLP AI 20 days\Day 1 - Python Data Science\A\K.txt")

array([[4., 5., 1., 6., 1., 6.],
       [1., 0., 3., 3., 1., 2.],
       [0., 5., 1., 1., 4., 3.]])

In [2]:
import pandas as pd
df = pd.read_csv("E:\Python\Road to OLP AI 20 days\Day 1 - Python Data Science\A\K.txt", header = None , sep=" ")
df
A = df.values
print(A)

[[4. 5. 1. 6. 1. 6.]
 [1. 0. 3. 3. 1. 2.]
 [0. 5. 1. 1. 4. 3.]]


In [6]:
import numpy as np
X = np.array([[1,2,3,4],
              [4,5,6,2],
              [7,8,9,1],
              [2,5,1,5]])
print(X[1,3])
print(X[1:3,1:3])

2
[[5 6]
 [8 9]]


In [7]:
print(X[:2,:2])

[[1 2]
 [4 5]]


In [8]:
print(X[-2:,-2:])

[[9 1]
 [1 5]]


In [9]:
print(X[[0,2],:])

[[1 2 3 4]
 [7 8 9 1]]


In [10]:
B = np.array(np.arange(12))
print("B: \n",B)
print("B.shape \n",B.shape)

B: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
B.shape 
 (12,)


In [11]:
# Dung B.reshape()
B.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
# Dung np.reshape()
np.reshape(B,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
B.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [14]:
B.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
B = np.reshape(B,(2,-1))
print(B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [16]:
# Khoi tao 1 buc anh ngau nhien co kich thuoc channels x width x height = 3 x 28 x 28
A = np.random.randint(0,255,size=(3,28,28))
print("A.shape" , A.shape)
# Chuyen channels ve cuoi
A = np.transpose(A,(1,2,0))
print("A transpose shape: ",A.shape)

A.shape (3, 28, 28)
A transpose shape:  (28, 28, 3)


In [25]:
A = np.random.randint(0,255,size=(28,28,3))
B = np.random.randint(0,255,size=(28,28,3))
print("A.shape" , A.shape)
print("B.shape" , B.shape)
AB = np.concatenate((A,B),axis=1)
print("shape after concatenate: ",AB.shape)

A.shape (28, 28, 3)
B.shape (28, 28, 3)
shape after concatenate:  (28, 56, 3)


In [26]:
np.stack([A,B]).shape

(2, 28, 28, 3)

In [28]:
A = np.random.randint(0,2,size=(1,2,3))
B = np.random.randint(0,2,size=(1,3))

# A.dot(B)

In [29]:
# Mo rong mang
B = np.expand_dims(B,axis = -1)
print("B new shape: ",B.shape)
print("A.dot(B) shape: ",A.dot(B).shape)

B new shape:  (1, 3, 1)
A.dot(B) shape:  (1, 2, 1, 1)


In [32]:
B = np.array([[0,1,2,3,4,5],
              [6,7,8,9,10,11]])
# Tim ra B.min()

B.min()

np.int64(0)

In [34]:
# Tim ra phan tu nho nhat cua B theo dong
B.max(axis=1)

array([ 5, 11])

In [35]:
A = np.array([[1,3,6],
              [2,7,9]])
B = np.array([[0,4,5],
             [1,6,10]])
# Tim cac phan tu maximum cua A va B o cung vi tri indice
np.maximum(A,B)

array([[ 1,  4,  6],
       [ 2,  7, 10]])

In [36]:
np.minimum(A,B)

array([[0, 3, 5],
       [1, 6, 9]])

In [37]:
# Tim ra indice co gia tri lon nhat cua vec to
A = np.array([1,5,3,2,4])
np.argmax(A)

np.int64(1)

In [38]:
A = np.array([[1,2],
              [3,4],
              [5,0],
              [2,1]])
np.argmax(A,axis=1)

array([1, 1, 0, 0])

In [45]:
B = np.array([[0.1, 0.2, 0.7],
              [0.6, 0.4, 0.0],
              [0.1, 0.5, 0.4],
              [0.3, 0.3, 0.4],
              [0.1, 0.8, 0.1]])
A = np.argmax(B,axis=1)
print(A)
labels_count = np.bincount(A)
for i,count in enumerate(labels_count):
    print(f"class {i}: {count} quan sat")

[2 0 1 2 1]
class 0: 1 quan sat
class 1: 2 quan sat
class 2: 2 quan sat


In [46]:
B = np.array([[0, 0, 1],
       [2, 3, 4],
       [4, 1, 2],
       [3, 2, 3],
       [1, 4, 0]])
np.argsort(B,axis=1)
B = B[:,::-1]
print(B)

[[1 0 0]
 [4 3 2]
 [2 1 4]
 [3 2 3]
 [0 4 1]]


In [47]:
np.random.seed(24)
data = np.random.randint(0,100,100)

train_size = int(0.7 * len(data))

tap_train = data[:train_size]
tap_test = data[train_size:]
print("Kich thuoc tap train : ",len(tap_train))
print("Tap train: ",tap_train)
print("Kich thuoc tap test : ",len(tap_test))
print("Tap test : ",tap_test)

Kich thuoc tap train :  70
Tap train:  [34  3 64 87 17 17  1 79  4 99 82 11 99 15 73 18  7 25 35 95 28  0 12 95
 33  1 60 55 70 97 81  6 46 65 47 89 74 35 64 27 97 33  3  4 65 10 41 56
 45  7  5 60 83 42  0 27 21 66 36 54 45 96 86 34 75 94 85 39 68 63]
Kich thuoc tap test :  30
Tap test :  [67 71  8 67 70 23 42 74 75 80 27 65  6 32 90 98 96 24 86 44 75 62 95 12
 21 42 76 35 36 38]


In [48]:
import numpy as np

A = np.array([[10, 1, 2],
              [9, 7, 4],
              [0, 2, 1]])

B = np.array([[2, 3, 4],
              [0, 4, 2],
              [3, 2, 1]])
AB = np.concatenate((A,B),axis=0)
print(AB)

[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]
 [ 2  3  4]
 [ 0  4  2]
 [ 3  2  1]]


In [50]:
np.reshape(A,(1,-1))

array([[10,  1,  2,  9,  7,  4,  0,  2,  1]])

In [52]:
print(A)

[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]]


In [53]:
labels = np.argmax(A,axis=1)
print(labels)

[0 0 1]


In [54]:
min_a = np.min(A,axis=0)
print(min_a)
max_a = np.max(A,axis=0)
print(max_a)
mean_a = np.mean(A,axis=0)
print(mean_a)
sum_a = np.sum(A,axis=0)
print(sum_a)

[0 1 1]
[10  7  4]
[6.33333333 3.33333333 2.33333333]
[19 10  7]
